apiVersion: v1
kind: Pod
metadata:
  name: egress-multi-router
  labels:
    name: egress-multi-router
  annotations:
    pod.network.openshift.io/assign-macvlan: "true"
spec:
  nodeSelector:
    router: 'egress-one-to-many'
  containers:
  - name: egress-router
    image: openshift3/ose-egress-router
    securityContext:
      privileged: true
    env:
    - name: EGRESS_SOURCE 
      value: 147.75.85.115
    - name: EGRESS_GATEWAY 
      value: 147.75.85.113
    - name: EGRESS_DESTINATION 
      value: |
        80 tcp 216.58.208.174
        555 tcp 147.75.40.2 80
        3306 tcp 147.75.33.1 30036
