apiVersion: v1
kind: Pod
metadata:
  name: get-ip-router
  labels:
    name: get-ip-router
  annotations:
    pod.network.openshift.io/assign-macvlan: "true"
spec:
  nodeSelector:
    router: 'egress-one-to-one'
  containers:
  - name: egress-router
    image: openshift3/ose-egress-router
    securityContext:
      privileged: true
    env:
    - name: EGRESS_SOURCE 
      value: 147.75.84.132
    - name: EGRESS_GATEWAY 
      value: 147.75.84.129
    - name: EGRESS_DESTINATION 
      value: 147.75.40.2
